# Generated by Django 5.0.1 on 2024-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='signed_up',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signed_up',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='signed_up',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signed_up',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
