# Generated by Django 5.0.1 on 2024-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_signed_up_address_signed_up_degree_signed_up_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signed_up',
            name='title',
            field=models.CharField(blank=True, default='mr.', max_length=255),
        ),
    ]
