# Generated by Django 5.0.1 on 2024-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_signed_up_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='signed_up',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='signed_up',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
