# Generated by Django 5.0.1 on 2024-01-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
