# Generated by Django 5.0.1 on 2024-01-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_appointment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
