# Generated by Django 5.0.1 on 2024-01-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_number', models.CharField(blank=True, max_length=255)),
                ('patient', models.CharField(blank=True, max_length=255)),
                ('patient_email', models.EmailField(blank=True, max_length=255)),
                ('patient_contact', models.CharField(blank=True, max_length=255)),
                ('doctor', models.CharField(blank=True, max_length=255)),
                ('doctor_email', models.EmailField(blank=True, max_length=255)),
                ('appointment_date', models.DateField(blank=True)),
                ('appointment_time', models.TimeField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('return_message', models.TextField(blank=True)),
                ('approval_status', models.BooleanField(default=False)),
                ('doctor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to='master.signed_up')),
                ('patient_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to='master.signed_up')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
