# Generated by Django 5.0.1 on 2024-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_remove_appointment_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signed_up',
            name='otp',
            field=models.CharField(blank=True, default='658734', max_length=10),
        ),
        migrations.AlterField(
            model_name='signed_up',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
