# Generated by Django 5.0.1 on 2024-01-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_signed_up_otp_alter_signed_up_is_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signed_up',
            old_name='is_activated',
            new_name='is_activated_patient',
        ),
        migrations.AddField(
            model_name='signed_up',
            name='is_activated_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
